
spring:
  datasource:
    url: jdbc:mysql://192.168.80.100:3306/dandelion-parent?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
mybatis:
  mapper-locations: classpath:/mapper/*.xml